### ISSUE TITLE
question about visual data 

### ISSUE THREAD

**Issue by kth0522** [AmandineBtto/NeRAF#1]
Hello,

First of all, thank you very much for sharing your code.

After reading your paper, it seems you used Habitat Sim to render higher resolution images of the scenes. However, I couldn't find the camera pose information for the training and testing splits.

Could you please share the pose information for each split of the visual data with json file?

Also, I wonder if NeRAF and AV-NeRF in the evaluation table used different visual data.

Thank you.

**Comment by AmandineBtto** [comment]
Hello, 

Thank you for your interest in NeRAF! 

Indeed, I've used Habitat Sim to generate images of the scenes. Examples of camera locations are given in the supplementary material. I've also added in the repository agent positions and rotations + simulation parameters to allow data generation with Habitat Sim. You can find them in the *data* folder. 

In the evaluation table, I took AV-NeRF results provided in their paper. The only information I found about their visual data for training on SoundSpaces is "We render RGB and depth images for each sound receiver pose using Habitat-Sim simulator. We maintain the same training/test split as NAF, allocating 90% data for training and 10% data for testing." (cf. section 5.1 (2)). 
From this, I suppose that they are training NeRF with RGB images corresponding to 90% of the sound receiver poses, which means they rely on a significantly larger number of training instances compared to what we are using in NeRAF. However, I am not entirely certain about this. Regardless, we use different visual data for Nerfacto training.

**Comment by kth0522** [comment]
Thank you for sharing detailed information!
