### ISSUE TITLE
split.json

### ISSUE THREAD

**Issue by kth0522** [AmandineBtto/NeRAF#2]
If it's not too much trouble, could you please share the metadata_AudioNeRF/split.json file?

Thank you.

**Comment by kth0522** [comment]
I made split.json using {room}_complete.pkl as in NAF. Is this how it works?

**Comment by AmandineBtto** [comment]
Hello @kth0522,

I've updated the data information. You can now find in the SoundSpaces the split.json files along with the code to pre-process the binaural RIRs.
